apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ingress-nginx-k-14
  namespace: "argocd"
spec:
  destination:
    name: k-14
    namespace: ingress-nginx
  project: default
  source:
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          extraArgs:
            enable-ssl-passthrough: true
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
