# host name are hardcoded for now. Future overrride should
# be stored/referenced inside customers Gitops repo.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rr737-zippy-k-14
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: oci://555935582951.dkr.ecr.us-west-2.amazonaws.com/rr737/charts
    chart: zippy
    targetRevision: 0.1.0-rc.9191e86
    helm:
      valuesObject:
        rr737-zippy:
          image:
            repository: 555935582951.dkr.ecr.us-west-2.amazonaws.com/rr737-zippy
          ingress:
            className: nginx
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/service-upstream: "true"
              cert-manager.io/issuer: letsencrypt-prod
            hosts:
              - host: rr737-zippy-k-14.gitopsmagic.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: rr737-zippy-tls
                hosts:
                  - rr737-zippy-k-14.gitopsmagic.com
  destination:
    name: k-14
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
