# host name are hardcoded for now. Future overrride should
# be stored/referenced inside customers Gitops repo.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {appName}-{clusterName}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: {chartRepoURL}
    chart: {appName}
    targetRevision: {targetRevision}
    helm:
      valuesObject:
        {appName}:
          image:
            repository: {imageRepoURL}/{appName}
          ingress:
            className: nginx
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/service-upstream: "true"
              cert-manager.io/issuer: letsencrypt-prod
            hosts:
              - host: {appName}-{clusterName}.gitopsmagic.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: {appName}-tls
                hosts:
                  - {appName}-{clusterName}.gitopsmagic.com
  destination:
    name: {clusterName}
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
